name: Lint code
on: [push, pull_request]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install 🔧
        run: |
          yarn install

      - name: Lint code 🔎
        run: |
          yarn run lint
